services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - "./mongodb:/data/db"
    environment:
      - MONDO_INITDB_ROOT_USERNAME=${MONDO_INITDB_ROOT_USERNAME}
      - MONDO_INITDB_ROOT_PASSWORD=${MONDO_INITDB_ROOT_PASSWORD}
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge
