services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - "mongodbata:/data/db"
    networks:
      - backend
    restart: always

networks:
  backend:
